/* AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by scripts/game/generate-startup-character-rulesets.mjs
 * Sources:
 * - imported/role-sources/3.6.7/role.c
 * - imported/role-sources/5.0/role.c
 * - imported/role-sources/slashem/role.c
 */

export const GENERATED_STARTUP_ROLE_OPTIONS = [
  "Archeologist",
  "Barbarian",
  "Caveman",
  "Healer",
  "Knight",
  "Monk",
  "Priest",
  "Rogue",
  "Ranger",
  "Samurai",
  "Tourist",
  "Valkyrie",
  "Wizard",
  "考古学家",
  "野蛮人",
  "穴居人",
  "医生",
  "骑士",
  "武僧",
  "牧师",
  "盗贼",
  "游侠",
  "武士",
  "游客",
  "女武神",
  "巫师",
  "Flame Mage",
  "Ice Mage",
  "Necromancer",
  "Undead Slayer",
  "Yeoman"
] as const;

export const GENERATED_STARTUP_RACE_OPTIONS = [
  "human",
  "elf",
  "dwarf",
  "gnome",
  "orc",
  "人类",
  "精灵",
  "矮人",
  "侏儒",
  "兽人",
  "doppelganger",
  "drow",
  "hobbit",
  "lycanthrope",
  "vampire"
] as const;

export const GENERATED_STARTUP_CHARACTER_RULESETS = {
  "3.6.7": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Healer",
      "Knight",
      "Monk",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Valkyrie",
      "Wizard"
    ],
    "races": [
      "human",
      "elf",
      "dwarf",
      "gnome",
      "orc"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Healer": {
        "races": [
          "human",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Knight": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Monk": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "human",
          "elf"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Valkyrie": {
        "races": [
          "human",
          "dwarf"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      }
    },
    "raceConstraints": {
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  },
  "5.0": {
    "roles": [
      "考古学家",
      "野蛮人",
      "穴居人",
      "医生",
      "骑士",
      "武僧",
      "牧师",
      "盗贼",
      "游侠",
      "武士",
      "游客",
      "女武神",
      "巫师"
    ],
    "races": [
      "人类",
      "精灵",
      "矮人",
      "侏儒",
      "兽人"
    ],
    "roleConstraints": {
      "考古学家": {
        "races": [
          "人类",
          "矮人",
          "侏儒"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "野蛮人": {
        "races": [
          "人类",
          "兽人"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "穴居人": {
        "races": [
          "人类",
          "矮人",
          "侏儒"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "医生": {
        "races": [
          "人类",
          "侏儒"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "骑士": {
        "races": [
          "人类"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "武僧": {
        "races": [
          "人类"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "牧师": {
        "races": [
          "人类",
          "精灵"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "盗贼": {
        "races": [
          "人类",
          "兽人"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "游侠": {
        "races": [
          "人类",
          "精灵",
          "侏儒",
          "兽人"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "武士": {
        "races": [
          "人类"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "游客": {
        "races": [
          "人类"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "女武神": {
        "races": [
          "人类",
          "矮人"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "巫师": {
        "races": [
          "人类",
          "精灵",
          "侏儒",
          "兽人"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      }
    },
    "raceConstraints": {
      "人类": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "精灵": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "矮人": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "侏儒": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "兽人": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  },
  "slashem": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Flame Mage",
      "Healer",
      "Ice Mage",
      "Knight",
      "Monk",
      "Necromancer",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Undead Slayer",
      "Valkyrie",
      "Wizard",
      "Yeoman"
    ],
    "races": [
      "doppelganger",
      "drow",
      "dwarf",
      "elf",
      "gnome",
      "hobbit",
      "human",
      "lycanthrope",
      "orc",
      "vampire"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "doppelganger",
          "dwarf",
          "elf",
          "gnome",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "human",
          "lycanthrope",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "doppelganger",
          "dwarf",
          "gnome",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Flame Mage": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Healer": {
        "races": [
          "doppelganger",
          "elf",
          "gnome",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Ice Mage": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Knight": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Monk": {
        "races": [
          "doppelganger",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Necromancer": {
        "races": [
          "doppelganger",
          "drow",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "doppelganger",
          "human",
          "lycanthrope",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "lycanthrope",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "doppelganger",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Undead Slayer": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "lycanthrope",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Valkyrie": {
        "races": [
          "doppelganger",
          "dwarf",
          "human"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Yeoman": {
        "races": [
          "elf",
          "hobbit",
          "human"
        ],
        "genders": [
          "male"
        ],
        "aligns": [
          "lawful"
        ]
      }
    },
    "raceConstraints": {
      "doppelganger": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "drow": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "hobbit": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "lycanthrope": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "vampire": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  }
} as const;
